#:kivy 1.3.0

<IconImage>:
    source: "images/{1}{0}.png".format(root.index, root.prefix)


<ColourButton>:
    IconImage:
        allow_stretch: True
        width: root.width - 10
        pos: root.x + 5, root.y + (root.height - self.height) / 2
        index: root.index

<Slider>:
    Label:
        center: root.center_x, root.center_y + root.height * 0.25
        text: str(int(root.value))
        halign: "center"
        text_size: root.width, None
